### ISSUE TITLE
Seasonal-Trend decomposition using LOESS (STL)

### ISSUE THREAD

**Issue by Sinansi** [JuliaStats/Loess.jl#37]
I couldn't find any library in Julia that actually does seasonal decomposition.

STL Decomposition seems complicated but if you know how to code Loess, I believe it would be much easier than having no prior knowledge at all.

I kindly ask the authors of this package to consider becoming the first Julia library that provide time series seasonal decomposition.

I am currently using STL Decomposition from Python Statsmodels via PyCall. But it is too slow.
https://www.statsmodels.org/devel/examples/notebooks/generated/stl_decomposition.html

Python Statsmodels is slow in general, I believe it is written only in Python.

Thank you!

**Comment by guilhermebodin** [comment]
Hi @Sinansi,  there is https://github.com/guilhermebodin/SeasonalTrendLoess.jl I think for now it is quite slow as it uses the exact procedure as described in the STL paper.

**Comment by Sinansi** [comment]
@guilhermebodin Thank you so much! I find this package very useful. Regarding the speed, atleast it is better than calling STL of statsmodels. Great work!
