### ISSUE TITLE
sample code does not run in Julia 1.4

### ISSUE THREAD

**Issue by ronb1000** [JuliaStats/Loess.jl#38]
Sample code doesn't work. Using Julia 1.4

vs = predict(model, us) raises error "no such method"

**Comment by tlnagy** [comment]
Are you sure you imported Loess?

```julia
using Loess

predict # predict is now imported
```

**Comment by ronb1000** [comment]
Hi Tamas

The problem is that there is conflict with another predict method. By itself the example works fine.

Is there a way to change the span?

It is also not clear to me how to plot the predict using plot.jl.

Ron Blanken
________________________________

**Comment by tlnagy** [comment]
If there's a conflict with another package, try using `Loess.predict` instead of `predict` to force the correct version. I don't personally use `Plots.jl`, I use `Gadfly`, but you should be able to pass your inputs and predicted values as x and y respectively.

**Comment by tlnagy** [comment]
If that didn't resolve your issue, please open a new issue!
