### ISSUE TITLE
Only accepts Float64

### ISSUE THREAD

**Issue by ayushpatnaikgit** [JuliaStats/Loess.jl#48]
It seems the package doesn't accept Float32 or Float16, even though the code is meant to accept AbstractFloats. 

I convert the inputs of the example to Array{Float32, 1}.  
```julia
using Loess
xs = 10 .* rand(100)
ys = sin.(xs) .+ 0.5 * rand(100)
xs = convert(Array{Float32,1}, xs)
ys = convert(Array{Float32,1}, ys)
```
When I call the loess function, it gives an error. 
```julia
model = loess(xs, ys)
```
```
ERROR: MethodError: no method matching build_kdtree(::Array{Float32,2}, ::Array{Int64,1}, ::Array{Float32,2}, ::Int64, ::Float64, ::Set{Array{Float32,1}})
```

If I convert the inputs back to Array{Float64, 1}, it works.

**Comment by ViralBShah** [comment]
ayushpatnaikgit Maybe you can help review and revive #53 to help fix this?
