### ISSUE TITLE
Predictions are not smooth

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/Loess.jl#61]
I'd say that the purpose of LOESS is to provide smooth predictions but that is not the case with the current implementation. Compare the LOESS lines produced by this package to the one from R. The tuning parameters should be identical.

### Loess.jl:
```julia
julia> using Loess, CairoMakie

julia> lf = loess(df.x, df.y);

julia> f, ax, l1 = scatter(df.x, df.y);

julia> lines!(ax, px, Loess.predict(lf, px), color=:black);

julia> f
```
<img width="804" alt="Skærmbillede 2023-03-16 kl  09 24 28" src="https://user-images.githubusercontent.com/505001/225570885-36615592-1064-4c2c-ae6e-a3484094feda.png">

### R:
```R
> df <- read.csv("/Users/andreasnoack/Downloads/loessdf.csv")
> plot(y ~ x, df)
> lf <- loess(y ~ x, df)
> lines(px, predict(lf, px))
```
<img width="660" alt="Skærmbillede 2023-03-16 kl  10 16 57" src="https://user-images.githubusercontent.com/505001/225570895-0edabc63-3cc4-4d43-975a-10c5228b58ed.png">

### Data
[loessdf.csv](https://github.com/JuliaStats/Loess.jl/files/10988881/loessdf.csv)

**Comment by bjarthur** [comment]
closed by https://github.com/JuliaStats/Loess.jl/pull/63 ?

**Comment by andreasnoack** [comment]
> closed by https://github.com/JuliaStats/Loess.jl/pull/63 ?

Yes!
